spring:
  main:
    web-application-type: none
  data:
    mongodb:
      host: 10.15.13.154
      port: 27017
      database: onehome
  rabbitmq:
    host: 10.15.13.154
    port: 5672
    username: root
    password: root
  redis:
    hostName: 10.15.13.154
    port: 6379
    password: root
  #    sentinel:
  #      master: mymaster
  #      nodes: localhost:26379

#config for application
application:
